export const TYPOGRAPHY = {
  DT1: {
    fontFamily: 'Jalnan',
    fontStyle: 'normal' as const,
    fontWeight: '700' as const,
    fontSize: 42,
    lineHeight: 52,
  },
  DT2: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal' as const,
    fontWeight: '700' as const,
    fontSize: 28,
    lineHeight: 34,
  },
  DT3: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal' as const,
    fontWeight: '700' as const,
    fontSize: 26,
    lineHeight: 34,
  },
  HT1: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal' as const,
    fontWeight: '700' as const,
    fontSize: 22,
    lineHeight: 32,
  },
  HT2: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal' as const,
    fontWeight: '700' as const,
    fontSize: 20,
    lineHeight: 30,
  },
  TT1: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal' as const,
    fontWeight: '700' as const,
    fontSize: 19,
    lineHeight: 28,
  },
  TT2: {
    fontFamily: 'Pretendard-SemiBold',
    fontStyle: 'normal' as const,
    fontWeight: '600' as const,
    fontSize: 18,
    lineHeight: 28,
  },
  TT3: {
    fontFamily: 'Pretendard-SemiBold',
    fontStyle: 'normal' as const,
    fontWeight: '600' as const,
    fontSize: 18,
    lineHeight: 28,
  },
  BT1: {
    fontFamily: 'Pretendard-Regular',
    fontStyle: 'normal' as const,
    fontWeight: '400' as const,
    fontSize: 17,
    lineHeight: 25,
  },
  BT2: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal' as const,
    fontWeight: '700' as const,
    fontSize: 15,
    lineHeight: 23,
  },
  BT3: {
    fontFamily: 'Pretendard-SemiBold',
    fontStyle: 'normal' as const,
    fontWeight: '600' as const,
    fontSize: 15,
    lineHeight: 23,
  },
  BT4: {
    fontFamily: 'Pretendard-Medium',
    fontStyle: 'normal' as const,
    fontWeight: '500' as const,
    fontSize: 15,
    lineHeight: 23,
  },
  BT5: {
    fontFamily: 'Pretendard-Regular',
    fontStyle: 'normal' as const,
    fontWeight: '500' as const,
    fontSize: 13,
    lineHeight: 20,
  },
};
